/**
 * Shared template-variable substitution for IndieKit email campaigns
 * and test sends. Variables come from creator templates (We're Live!,
 * 48-Hour Countdown, Backers Thanks, etc.) and the manual variable
 * picker in the email dialog.
 *
 * Supports all the variables our pre-built templates use:
 *   {{FIRST_NAME}}    — recipient's first name (or "there" fallback)
 *   {{NAME}}          — recipient's full name (or "there" fallback)
 *   {{PROJECT_NAME}}  — project title
 *   {{PROJECT_URL}}   — project URL (plain text, intended to live
 *                       inside an existing <a href="">…</a>)
 *   {{PROJECT_LINK}}  — full HTML anchor: <a href=URL>project title</a>
 *   {{PRELAUNCH_URL}} — prelaunch page URL (plain text)
 *   {{PRELAUNCH_LINK}}— full HTML anchor to prelaunch page
 *   {{CREATOR_NAME}}  — creator's display name
 *
 * Case-insensitive and whitespace-tolerant: {{first_name}},
 * {{ First_Name }}, and {{FIRST_NAME}} all work.
 *
 * XSS notes: the body is trusted HTML from the TipTap editor.
 * Variable VALUES come from user input (project title, creator name,
 * subscriber name) so they MUST be escaped before splicing into HTML.
 * For the *_LINK variants we generate the anchor ourselves; the URL
 * and visible text are both escaped, so the output is a complete
 * safe HTML snippet.
 */

/**
 * Pick a sensible "first name" for use in {{FIRST_NAME}} substitution.
 *
 * Falls through these sources in order so subscribers with imperfect
 * list data still get something personal-looking:
 *
 *   1. First word of the explicit name (e.g. "John Smith" → "John",
 *      "Mike" → "Mike"). Strips a trailing comma so "Smith, Mike"
 *      lands on "Smith" rather than "Smith,".
 *   2. Local part of the email address, prettified. "john.smith@…"
 *      → "John". "jdoe123@…" → "Jdoe123".
 *   3. The literal "Friend" as a last resort so we never emit a
 *      naked greeting like ", the wait is over!"
 */
export function extractFirstName(
  name: string | null | undefined,
  email?: string | null | undefined
): string {
  // 1. Try the name field first.
  if (name) {
    const trimmed = name.trim().replace(/,$/, "");
    if (trimmed) {
      const firstWord = trimmed.split(/\s+/)[0];
      if (firstWord) return firstWord;
    }
  }

  // 2. Fall back to the email's local part, capitalized. Drop everything
  // after a dot/underscore/plus so "john.smith+promos@…" still reads
  // as "John" rather than the whole local part.
  if (email) {
    const local = email.split("@")[0];
    if (local) {
      const cleaned = local.split(/[._+\-]/)[0];
      if (cleaned) {
        return cleaned.charAt(0).toUpperCase() + cleaned.slice(1);
      }
    }
  }

  // 3. Last resort.
  return "Friend";
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export interface TemplateVars {
  firstName?: string | null;
  fullName?: string | null;
  /** Recipient email — used as a fallback source for FIRST_NAME when the
   * subscriber's name field is empty. The local part before the @ gets
   * cleaned up and capitalized. */
  recipientEmail?: string | null;
  projectName?: string;
  projectUrl?: string;
  prelaunchUrl?: string;
  creatorName?: string;
}

/**
 * Build a single regex that matches {{NAME}} with arbitrary case and
 * optional inner whitespace, e.g. {{first_name}}, {{ FirstName }} —
 * note we deliberately accept both `FIRST_NAME` and `FIRSTNAME` for
 * each token so creators don't have to remember underscores.
 */
function tokenRegex(token: string): RegExp {
  // FIRST_NAME → also accept FIRSTNAME (underscore optional)
  const withoutUnderscore = token.replace(/_/g, "");
  const alts =
    token === withoutUnderscore ? token : `(?:${token}|${withoutUnderscore})`;
  return new RegExp(`\\{\\{\\s*${alts}\\s*\\}\\}`, "gi");
}

/**
 * Replace template variables in either the subject line or the HTML
 * body. The same function works for both — we just only emit HTML
 * anchors for the *_LINK variants, which subjects don't generally
 * use anyway.
 */
export function resolveTemplateVars(text: string, vars: TemplateVars): string {
  if (!text) return text;

  const projectName = vars.projectName?.trim() || "";
  const projectUrl = vars.projectUrl?.trim() || "";
  const prelaunchUrl = vars.prelaunchUrl?.trim() || "";
  const creatorName = vars.creatorName?.trim() || "";

  // Build link HTML — generated by us, so escape inputs and emit safe HTML.
  const projectLink = projectUrl
    ? `<a href="${escapeHtml(projectUrl)}">${escapeHtml(projectName || projectUrl)}</a>`
    : "";
  const prelaunchLink = prelaunchUrl
    ? `<a href="${escapeHtml(prelaunchUrl)}">${escapeHtml(projectName || prelaunchUrl)}</a>`
    : "";

  let result = text;

  // CRITICAL: only substitute FIRST_NAME / NAME when recipient context
  // was actually provided. The campaign batch send calls this function
  // TWICE — once at the campaign level (no recipient) to pre-resolve
  // project-level vars, then once per recipient with their name. If
  // we ran the FIRST_NAME path on the campaign-level call, it would
  // hit the extractFirstName(null,null) → "Friend" fallback and bake
  // "Friend" into the template, leaving nothing for the per-recipient
  // pass to substitute. Skip the recipient-level tokens here when no
  // recipient was passed; the next pass will fill them in.
  const hasRecipientContext = !!(
    vars.firstName ||
    vars.fullName ||
    vars.recipientEmail
  );
  if (hasRecipientContext) {
    const firstName =
      vars.firstName?.trim() ||
      extractFirstName(vars.fullName ?? null, vars.recipientEmail ?? null);
    const fullName = vars.fullName?.trim() || firstName;
    result = result
      .replace(tokenRegex("FIRST_NAME"), escapeHtml(firstName))
      .replace(tokenRegex("NAME"), escapeHtml(fullName));
  }

  return result
    .replace(tokenRegex("PROJECT_NAME"), escapeHtml(projectName))
    .replace(tokenRegex("PROJECT_URL"), escapeHtml(projectUrl))
    .replace(tokenRegex("PROJECT_LINK"), projectLink)
    .replace(tokenRegex("PRELAUNCH_URL"), escapeHtml(prelaunchUrl))
    .replace(tokenRegex("PRELAUNCH_LINK"), prelaunchLink)
    .replace(tokenRegex("CREATOR_NAME"), escapeHtml(creatorName));
}

/**
 * Subject-line variant: strips CR/LF (RFC 5322 forbids them in
 * headers — anything that slips through becomes a "header injection"
 * vector) and does NOT inject HTML, so no escaping of anchors etc.
 * Plain-text substitution only.
 */
export function resolveTemplateVarsForSubject(text: string, vars: TemplateVars): string {
  if (!text) return text;
  const stripped = text.replace(/[\r\n]/g, "");

  const firstName =
    vars.firstName?.trim() ||
    extractFirstName(vars.fullName ?? null, vars.recipientEmail ?? null);
  const fullName = vars.fullName?.trim() || firstName;
  const projectName = (vars.projectName || "").replace(/[\r\n]/g, "");
  const projectUrl = (vars.projectUrl || "").replace(/[\r\n]/g, "");
  const prelaunchUrl = (vars.prelaunchUrl || "").replace(/[\r\n]/g, "");
  const creatorName = (vars.creatorName || "").replace(/[\r\n]/g, "");

  return stripped
    .replace(tokenRegex("FIRST_NAME"), firstName.replace(/[\r\n]/g, ""))
    .replace(tokenRegex("NAME"), fullName.replace(/[\r\n]/g, ""))
    .replace(tokenRegex("PROJECT_NAME"), projectName)
    .replace(tokenRegex("PROJECT_URL"), projectUrl)
    .replace(tokenRegex("PROJECT_LINK"), projectUrl) // subject can't have anchor — fall back to URL
    .replace(tokenRegex("PRELAUNCH_URL"), prelaunchUrl)
    .replace(tokenRegex("PRELAUNCH_LINK"), prelaunchUrl)
    .replace(tokenRegex("CREATOR_NAME"), creatorName);
}
