/**
 * Shared template-variable substitution for IndieKit email campaigns
 * and test sends. Variables come from creator templates (We're Live!,
 * 48-Hour Countdown, Backers Thanks, etc.) and the manual variable
 * picker in the email dialog.
 *
 * Supports all the variables our pre-built templates use:
 *   {{FIRST_NAME}}    — recipient's first name (or "there" fallback)
 *   {{NAME}}          — recipient's full name (or "there" fallback)
 *   {{PROJECT_NAME}}  — project title
 *   {{PROJECT_URL}}   — project URL (plain text, intended to live
 *                       inside an existing <a href="">…</a>)
 *   {{PROJECT_LINK}}  — full HTML anchor: <a href=URL>project title</a>
 *   {{PRELAUNCH_URL}} — prelaunch page URL (plain text)
 *   {{PRELAUNCH_LINK}}— full HTML anchor to prelaunch page
 *   {{CREATOR_NAME}}  — creator's display name
 *
 * Case-insensitive and whitespace-tolerant: {{first_name}},
 * {{ First_Name }}, and {{FIRST_NAME}} all work.
 *
 * XSS notes: the body is trusted HTML from the TipTap editor.
 * Variable VALUES come from user input (project title, creator name,
 * subscriber name) so they MUST be escaped before splicing into HTML.
 * For the *_LINK variants we generate the anchor ourselves; the URL
 * and visible text are both escaped, so the output is a complete
 * safe HTML snippet.
 */

export function extractFirstName(name: string | null | undefined): string {
  if (!name) return "there";
  const trimmed = name.trim();
  if (!trimmed) return "there";
  // First word before any whitespace. "John Smith" → "John".
  // "John-Paul" stays "John-Paul" (hyphenated first name).
  const firstWord = trimmed.split(/\s+/)[0];
  return firstWord || "there";
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export interface TemplateVars {
  firstName?: string | null;
  fullName?: string | null;
  projectName?: string;
  projectUrl?: string;
  prelaunchUrl?: string;
  creatorName?: string;
}

/**
 * Build a single regex that matches {{NAME}} with arbitrary case and
 * optional inner whitespace, e.g. {{first_name}}, {{ FirstName }} —
 * note we deliberately accept both `FIRST_NAME` and `FIRSTNAME` for
 * each token so creators don't have to remember underscores.
 */
function tokenRegex(token: string): RegExp {
  // FIRST_NAME → also accept FIRSTNAME (underscore optional)
  const withoutUnderscore = token.replace(/_/g, "");
  const alts =
    token === withoutUnderscore ? token : `(?:${token}|${withoutUnderscore})`;
  return new RegExp(`\\{\\{\\s*${alts}\\s*\\}\\}`, "gi");
}

/**
 * Replace template variables in either the subject line or the HTML
 * body. The same function works for both — we just only emit HTML
 * anchors for the *_LINK variants, which subjects don't generally
 * use anyway.
 */
export function resolveTemplateVars(text: string, vars: TemplateVars): string {
  if (!text) return text;

  const firstName = vars.firstName?.trim() || extractFirstName(vars.fullName ?? null);
  const fullName = vars.fullName?.trim() || firstName;
  const projectName = vars.projectName?.trim() || "";
  const projectUrl = vars.projectUrl?.trim() || "";
  const prelaunchUrl = vars.prelaunchUrl?.trim() || "";
  const creatorName = vars.creatorName?.trim() || "";

  // Build link HTML — generated by us, so escape inputs and emit safe HTML.
  const projectLink = projectUrl
    ? `<a href="${escapeHtml(projectUrl)}">${escapeHtml(projectName || projectUrl)}</a>`
    : "";
  const prelaunchLink = prelaunchUrl
    ? `<a href="${escapeHtml(prelaunchUrl)}">${escapeHtml(projectName || prelaunchUrl)}</a>`
    : "";

  return text
    .replace(tokenRegex("FIRST_NAME"), escapeHtml(firstName))
    .replace(tokenRegex("NAME"), escapeHtml(fullName))
    .replace(tokenRegex("PROJECT_NAME"), escapeHtml(projectName))
    .replace(tokenRegex("PROJECT_URL"), escapeHtml(projectUrl))
    .replace(tokenRegex("PROJECT_LINK"), projectLink)
    .replace(tokenRegex("PRELAUNCH_URL"), escapeHtml(prelaunchUrl))
    .replace(tokenRegex("PRELAUNCH_LINK"), prelaunchLink)
    .replace(tokenRegex("CREATOR_NAME"), escapeHtml(creatorName));
}

/**
 * Subject-line variant: strips CR/LF (RFC 5322 forbids them in
 * headers — anything that slips through becomes a "header injection"
 * vector) and does NOT inject HTML, so no escaping of anchors etc.
 * Plain-text substitution only.
 */
export function resolveTemplateVarsForSubject(text: string, vars: TemplateVars): string {
  if (!text) return text;
  const stripped = text.replace(/[\r\n]/g, "");

  const firstName = vars.firstName?.trim() || extractFirstName(vars.fullName ?? null);
  const fullName = vars.fullName?.trim() || firstName;
  const projectName = (vars.projectName || "").replace(/[\r\n]/g, "");
  const projectUrl = (vars.projectUrl || "").replace(/[\r\n]/g, "");
  const prelaunchUrl = (vars.prelaunchUrl || "").replace(/[\r\n]/g, "");
  const creatorName = (vars.creatorName || "").replace(/[\r\n]/g, "");

  return stripped
    .replace(tokenRegex("FIRST_NAME"), firstName.replace(/[\r\n]/g, ""))
    .replace(tokenRegex("NAME"), fullName.replace(/[\r\n]/g, ""))
    .replace(tokenRegex("PROJECT_NAME"), projectName)
    .replace(tokenRegex("PROJECT_URL"), projectUrl)
    .replace(tokenRegex("PROJECT_LINK"), projectUrl) // subject can't have anchor — fall back to URL
    .replace(tokenRegex("PRELAUNCH_URL"), prelaunchUrl)
    .replace(tokenRegex("PRELAUNCH_LINK"), prelaunchUrl)
    .replace(tokenRegex("CREATOR_NAME"), creatorName);
}
